#
# في هذا الملف ستجد كل المتغيرات التي تتحكم في إعدادات المدونة، شخصّها على حسب متطلباتك
#

# اسم المدونة الذي سيظهر في الأعلى
name: صويلح رزاق

# وصف قصير للمدونة والذي سيظهر تحت اسمها وكجزء من عنوان المدونة في محركات البحث
description: ""

# رابط صورة المدونة
# لإستخدام صورة هويتك في GitHub ضع https://github.com/<اسم_المستخدم>.png في المتغير، مثلا لهويتي الشخصية أستخدم:
# avatar: https://github.com/a3ammar.png
# ولإخفاء الصورة نهائيًا احذف الرابط من المتغير
avatar: https://raw.githubusercontent.com/AboTyim/abotyim.github.io/master/images/logo.jpg


#
# المتغيرات الآتية هي خيارية، عدل عليها إذا أردت تخصيص أكثر للمدونة
#

# لكل هوية تضعها هنا ستظهر أيقونة في أسفل المدونة
footer-links:
  email: rezazsouilah@gmail.com
  facebook: https://www.facebook.com/rezak.souilah.5/
  github: https://github.com/souilahrezak
  linkedin: https://www.linkedin.com/in/souilah-rezak-ens-kouba-b01336176/
  rss: https://abotyim.github.io/feed.xml # ضع أي قيمة هنا لتظهر أيقونة RSS
  twitter: https://twitter.com/RezakSouilah
  stackoverflow: # هويتك في stackoverflow مثلا: "users/50476/bart-kiers"
  youtube: https://www.youtube.com/channel/UC5koK8t_zhHArmZ1WWF80MQ
  


# ضع الاسم Disqus القصير الخاص بك (الاسم القصير وليس اسم المستخدم) لتفعيل الردود على المدونة
# ستجد الاسم القصير الخاص بك في إعدادات حسابك في Disqus
# disqus: abotyim

# إذا أردت تفعيل إحصاءات الزوار في Google Analytics أدخل المعرف الخاص بك (مثلاً UA-2110908-2)
# google_analytics: UA-133736790-1

# عنوان موقعك مثلاً http://barryclark.github.io
# يستخدم هذا المتغير في الـRSS والـSitemap.xml
url: https://souilahrezak.github.io

# إذا كانت المدونة خاصة للصفحات المشاريع في GitHub (http://yourusername.github.io/repository-name مثلاً) عدل هذا المتغير ليطابق اسم المشروع
baseurl: ""


#
# هذه المتغيرات خاصة بـJekyll ولا أنصح بتعديلها، لذلك لا حاجة لشرحها
#

permalink: /:title/
# permalink: /:categories/:title/

paginate: 5
paginate_path: "/page/:num"

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: "highlight"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
